### ISSUE TITLE
Getting 403 when login.

### ISSUE THREAD

**Issue by junqdu** [kmoe/slack-pokebot#29]
2016-07-29T21:50:10.008997+00:00 app[worker.1]: [i] Logging with user: 
2016-07-29T21:50:10.588132+00:00 app[worker.1]: undefined
2016-07-29T21:50:10.594204+00:00 app[worker.1]: error:  Error: 403 error from server
2016-07-29T21:50:10.594207+00:00 app[worker.1]:     at IncomingMessage.emit (events.js:185:7)
2016-07-29T21:50:10.594208+00:00 app[worker.1]:     at endReadableNT (_stream_readable.js:975:12)
2016-07-29T21:50:10.615285+00:00 app[worker.1]:

**Comment by jakeboyles** [comment]
Could be an issue if your trying to login using your ptc account when its set to google or also possible a 2 step auth problem if your using google. Which are you trying to use to login?

**Comment by junqdu** [comment]
@jakeboyles I am trying to use google, and I do have 2 step auth

**Comment by jakeboyles** [comment]
@junqdu https://github.com/Armax/Pokemon-GO-node-api/issues/176

**Comment by junqdu** [comment]
@jakeboyles Changed to a different account, still getting 403 :(
2016-07-29T22:18:19.556805+00:00 heroku[worker.1]: State changed from starting to up
2016-07-29T22:18:21.171072+00:00 app[worker.1]: 
2016-07-29T22:18:21.171088+00:00 app[worker.1]: > slack-pokebot@1.0.0 start /app
2016-07-29T22:18:21.171089+00:00 app[worker.1]: > echo {} > .data && node index.js
2016-07-29T22:18:21.171090+00:00 app[worker.1]: 
2016-07-29T22:18:21.760219+00:00 app[worker.1]: info: Logger Initialised
2016-07-29T22:18:21.772624+00:00 app[worker.1]: info: Initialised
2016-07-29T22:18:22.018576+00:00 app[worker.1]: undefined
2016-07-29T22:18:22.021335+00:00 app[worker.1]: error:  Error: 403 error from server
2016-07-29T22:18:22.021338+00:00 app[worker.1]:     at IncomingMessage.emit (events.js:185:7)
2016-07-29T22:18:22.021341+00:00 app[worker.1]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-07-29T22:18:22.021342+00:00 app[worker.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-07-29T22:18:22.034058+00:00 app[worker.1]: 
2016-07-29T22:18:22.042748+00:00 app[worker.1]: npm ERR! Linux 3.13.0-91-generic
2016-07-29T22:18:22.043039+00:00 app[worker.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-07-29T22:18:22.043249+00:00 app[worker.1]: npm ERR! node v6.3.1
2016-07-29T22:18:22.043503+00:00 app[worker.1]: npm ERR! npm  v3.10.3
2016-07-29T22:18:22.044112+00:00 app[worker.1]: npm ERR! 
2016-07-29T22:18:22.044232+00:00 app[worker.1]: npm ERR! Failed at the slack-pokebot@1.0.0 start script 'echo {} > .data && node index.js'.
2016-07-29T22:18:22.044392+00:00 app[worker.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-07-29T22:18:22.044511+00:00 app[worker.1]: npm ERR! If you do, this is most likely a problem with the slack-pokebot package,
2016-07-29T22:18:22.044630+00:00 app[worker.1]: npm ERR! not with npm itself.
2016-07-29T22:18:22.044760+00:00 app[worker.1]: npm ERR! Tell the author that this fails on your system:
2016-07-29T22:18:22.054702+00:00 app[worker.1]: npm ERR!     /app/npm-debug.log
2016-07-29T22:18:22.149270+00:00 heroku[worker.1]: Process exited with status 1
2016-07-29T22:18:22.158900+00:00 heroku[worker.1]: State changed from up to crashed
2016-07-29T22:18:22.044112+00:00 app[worker.1]: npm ERR! 
2016-07-29T22:18:22.044760+00:00 app[worker.1]: npm ERR! Tell the author that this fails on your system:
2016-07-29T22:18:22.054306+00:00 app[worker.1]: 
2016-07-29T22:18:22.045499+00:00 app[worker.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-07-29T22:18:22.054566+00:00 app[worker.1]: npm ERR! Please include the following file with any support request:
2016-07-29T22:18:22.045059+00:00 app[worker.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-07-29T22:18:22.045765+00:00 app[worker.1]: npm ERR! There is likely additional logging output above.
2016-07-29T22:18:22.149270+00:00 heroku[worker.1]: Process exited with status 1

**Comment by junqdu** [comment]
@jakeboyles Thanks for the help, I found answer here https://github.com/Armax/Pokemon-GO-node-api/issues/94

I used the app password instead.

**Comment by kmoe** [comment]
Thanks guys, will make sure I specify to use an app password for Google accounts when I update the README.
